### ISSUE TITLE
A typo?

### ISSUE THREAD

**Issue by utkutpcgl** [Haoqing-Wang/LocalMIM#4]
I guess there is a minor typo in the pretrain code:
https://github.com/Haoqing-Wang/LocalMIM/blob/314a6e558a8c47bf0ef146235e2ced8d01e27fe6/ViT/run_pretrain.py#L44

This should be rather "MIM_vit_large_patch16" I guess?

**Comment by Haoqing-Wang** [comment]
Yes, thanks for reminding me. In fact, this argument is typically defined in the running script.
